Dataset: alunos.csv (dados fictícios com
nome, idade, nota, curso)

Tarefas:
1. Carregar o arquivo CSV com Pandas
2. Mostrar as primeiras 5 linhas
3. Usar info() e describe()
4. Selecionar apenas as colunas nome e
nota
5. Filtrar alunos com nota >= 7

In [7]:
with open("alunos.csv", "w") as arquivo:
    arquivo.write("nome,idade,nota,curso\n")
    arquivo.write("Ana,20,10,BCC\n")
    arquivo.write("Beatriz,21,7,Enc\n")
    arquivo.write("Camila,20,9.5,SI\n")
    arquivo.write("Daniela,20,9,BCC\n")
    arquivo.write("Elisa,22,7,Enc\n")

import pandas as pd

alunos = pd.read_csv("alunos.csv")
alunos.head(5)

      nome  idade  nota curso
0      Ana     20  10.0   BCC
1  Beatriz     21   7.0   Enc
2   Camila     20   9.5    SI
3  Daniela     20   9.0   BCC
4    Elisa     22   7.0   Enc

In [6]:
alunos.info()
alunos.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    5 non-null      object
 1   idade   5 non-null      int64
 2   nota    5 non-null      float64
 3   curso   5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

           idade       nota
count   5.000000   5.000000
mean   20.600000   8.500000
std     0.894427   1.414214
min    20.000000   7.000000
25%    20.000000   7.000000
50%    20.000000   9.000000
75%    21.000000   9.500000
max    22.000000  10.000000

In [5]:
print(alunos[['nome','nota']])
print(alunos[alunos['nota'] > 7])

      nome  nota
0      Ana  10.0
1  Beatriz   7.0
2   Camila   9.5
3  Daniela   9.0
4    Elisa   7.0
      nome  idade  nota curso
0      Ana     20  10.0   BCC
2   Camila     20   9.5    SI
3  Daniela     20   9.0   BCC