# Cria o arquivo .csv

In [14]:
import pandas as pd
import random

random.seed(42)

nomes = [
    "Ana", "Bruno", "Carlos", "Daniela", "Eduardo", "Fernanda", "Gabriel",
    "Helena", "Igor", "Juliana", "Kleber", "Larissa", "Marcos", "Natália",
    "Otávio", "Patrícia", "Rafael", "Sabrina", "Thiago", "Vanessa"
]

sobrenomes = [
    "Silva", "Souza", "Oliveira", "Pereira", "Costa", "Rodrigues",
    "Almeida", "Nascimento", "Lima", "Araújo"
]

cursos = [
    "Engenharia", "Direito", "Medicina", "Computação", "Administração",
    "Arquitetura", "Economia", "Psicologia"
]

dados = []

for i in range(100):
    nome_completo = f"{random.choice(nomes)} {random.choice(sobrenomes)}"
    idade = random.randint(17, 30)
    nota = round(random.uniform(0, 10), 1)
    curso = random.choice(cursos)

    dados.append({
        "nome": nome_completo,
        "idade": idade,
        "nota": nota,
        "curso": curso
    })

df = pd.DataFrame(dados)

df.to_csv("alunos.csv", index=False)

df.head()

              nome  idade  nota          curso
0    Daniela Silva     28   2.8     Computação
1    Eduardo Souza     27   7.4        Direito
2   Thiago Almeida     17   0.3     Computação
3      Helena Lima     26   0.3     Computação
4  Sabrina Almeida     20   4.5  Administração

# Carrega o csv

In [15]:
df = pd.read_csv("alunos.csv")
df

                 nome  idade  nota          curso
0       Daniela Silva     28   2.8     Computação
1       Eduardo Souza     27   7.4        Direito
2      Thiago Almeida     17   0.3     Computação
3         Helena Lima     26   0.3     Computação
4     Sabrina Almeida     20   4.5  Administração
..                ...    ...   ...            ...
95  Otávio Nascimento     24   6.8     Psicologia
96     Fernanda Souza     21   5.2    Arquitetura
97     Carlos Pereira     27   3.1     Computação
98      Eduardo Silva     17   2.4     Psicologia
99      Vanessa Souza     24   4.1     Computação

[100 rows x 4 columns]

# Mostra as 5 primeiras linhas

In [16]:
df.head()

              nome  idade  nota          curso
0    Daniela Silva     28   2.8     Computação
1    Eduardo Souza     27   7.4        Direito
2   Thiago Almeida     17   0.3     Computação
3      Helena Lima     26   0.3     Computação
4  Sabrina Almeida     20   4.5  Administração

# Uso de info() e describe()

In [17]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    100 non-null    object
 1   idade   100 non-null    int64
 2   nota    100 non-null    float64
 3   curso   100 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 3.3+ KB

            idade        nota
count  100.000000  100.000000
mean    24.210000    4.575000
std      4.028422    2.849752
min     17.000000    0.100000
25%     21.000000    2.275000
50%     25.000000    4.100000
75%     27.250000    7.225000
max     30.000000   10.000000

# Selecionar as colunas nomes e nota

In [18]:
df[["nome", "nota"]]

                 nome  nota
0       Daniela Silva   2.8
1       Eduardo Souza   7.4
2      Thiago Almeida   0.3
3         Helena Lima   0.3
4     Sabrina Almeida   4.5
..                ...   ...
95  Otávio Nascimento   6.8
96     Fernanda Souza   5.2
97     Carlos Pereira   3.1
98      Eduardo Silva   2.4
99      Vanessa Souza   4.1

[100 rows x 2 columns]

# Filtrar alunos com nota >= 7

In [19]:
df[df["nota"] >= 7]

                  nome  idade  nota          curso
1        Eduardo Souza     27   7.4        Direito
7         Marcos Souza     22   8.5  Administração
9          Carlos Lima     21   8.3    Arquitetura
16        Kleber Silva     20   8.2    Arquitetura
18  Gabriel Nascimento     23   8.8     Psicologia
24        Rafael Costa     25   8.6     Engenharia
29       Fernanda Lima     29   9.2     Engenharia
34        Gabriel Lima     29   7.3     Computação
46   Carlos Nascimento     29   8.6        Direito
52         Thiago Lima     17   7.5     Engenharia
54          Bruno Lima     18   8.5        Direito
55       Vanessa Souza     27   8.6       Economia
58        Igor Pereira     27   7.2     Computação
60    Otávio Rodrigues     29   9.4     Engenharia
61       Otávio Araújo     26  10.0        Direito
64       Sabrina Costa     26   9.8     Engenharia
66          Igor Souza     18   7.4       Medicina
70     Kleber Oliveira     27   9.8       Medicina
72       Daniela Souza     28   9.0     Engenharia
74         Bruno Costa     22   9.0     Engenharia
77     Helena Oliveira     29   8.1       Economia
78        Ana Oliveira     28   9.2       Economia
79        Helena Costa     19   7.9        Direito
81    Otávio Rodrigues     21   8.2     Computação
89     Larissa Almeida     18   9.5    Arquitetura
90   Vanessa Rodrigues     27   8.5  Administração