Ex 1 - criando o arquivo csv

In [2]:
import pandas as pd

# Criando os dados fictícios
dados = {
    "nome": ["Ana", "Bruno", "Carla", "Daniel", "Eduarda", "Fabio", "Gisele", "Hugo", "Igor", "Julia"],
    "idade": [20, 22, 19, 21, 23, 20, 22, 21, 24, 19],
    "nota": [8.5, 6.0, 9.2, 5.5, 7.8, 10.0, 6.5, 8.0, 4.5, 9.0],
    "curso": ["Engenharia", "Direito", "Medicina", "TI", "Artes", "TI", "Engenharia", "Direito", "Artes", "Medicina"]
}

# Transformando em DataFrame e salvando em CSV
df_inicial = pd.DataFrame(dados)
df_inicial.to_csv("alunos.csv", index=False)

print("Arquivo 'alunos.csv' criado com sucesso!")

Arquivo 'alunos.csv' criado com sucesso!

Manipulando dados

In [3]:
# 1. Carregar o arquivo CSV
df = pd.read_csv("alunos.csv")

# 2. Mostrar as primeiras 5 linhas
print("--- Primeiras 5 linhas ---")
df.head()

--- Primeiras 5 linhas ---

      nome  idade  nota       curso
0      Ana     20   8.5  Engenharia
1    Bruno     22   6.0     Direito
2    Carla     19   9.2    Medicina
3   Daniel     21   5.5          TI
4  Eduarda     23   7.8       Artes

In [4]:

# 3. Usar info() e describe()
print("\n--- Informações do Dataset (info) ---")
df.info()

print("\n--- Resumo Estatístico (describe) ---")
df.describe()

--- Informações do Dataset (info) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    10 non-null     object
 1   idade   10 non-null     int64
 2   nota    10 non-null     float64
 3   curso   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

--- Resumo Estatístico (describe) ---

          idade       nota
count  10.00000  10.000000
mean   21.10000   7.500000
std     1.66333   1.794436
min    19.00000   4.500000
25%    20.00000   6.125000
50%    21.00000   7.900000
75%    22.00000   8.875000
max    24.00000  10.000000

In [5]:
# 4. Selecionar apenas as colunas nome e nota
colunas_selecionadas = df[["nome", "nota"]]
print("\n--- Apenas Nome e Nota ---")
colunas_selecionadas.head()

--- Apenas Nome e Nota ---

      nome  nota
0      Ana   8.5
1    Bruno   6.0
2    Carla   9.2
3   Daniel   5.5
4  Eduarda   7.8

In [8]:


# 5. Filtrar alunos com nota >= 7
aprovados = df[df["nota"] >= 7]
aprovados.head(10)

      nome  idade  nota       curso
0      Ana     20   8.5  Engenharia
2    Carla     19   9.2    Medicina
4  Eduarda     23   7.8       Artes
5    Fabio     20  10.0          TI
7     Hugo     21   8.0     Direito
9    Julia     19   9.0    Medicina